### ISSUE TITLE
Error when running command "make"

### ISSUE THREAD

**Issue by yiyayo-wqh** [cloud-key-store/keystore#1]
Hello,
       
When I follow the steps :
![image](https://user-images.githubusercontent.com/43172897/78886550-fd31cc80-7a90-11ea-8da0-b036d0e5c2a7.png)

, it shows error :
![image](https://user-images.githubusercontent.com/43172897/78886642-27838a00-7a91-11ea-9fa2-bfd6ef87fa0f.png)

I'm sure that i have cloned the 3rd party libraries 'sgx-utils'  and the Makefile 'Lib_Dir' variable points to the right directory.

When i check the Makefile, i find the lib dependencies that not in the 'sgx-utils' project (I do not find the suitable library): 
![image](https://user-images.githubusercontent.com/43172897/78886587-0a4ebb80-7a91-11ea-8b1f-591cd3b55a2f.png)

so, how can I successfully make the project?

Looking forward to your reply and best wishes!
 Qing Hao,Wang

**Comment by akurniko** [comment]
Hi,

thanks for interest in the project. Indeed, this library is missing. The
base64 library can be obtained from here: http://libb64.sourceforge.net/
Pull requests on updating the documentation are welcome!

Cheers,
-Arseny

чт, 9 апр. 2020 г. в 13:30, wangqinghao123 <notifications@github.com>:

**Comment by yiyayo-wqh** [comment]
Thanks @akurniko ， 

I will try to get this lib and link it.  

Thank you for your kinds!

**Comment by yiyayo-wqh** [comment]
Hello @akurniko ,

I downloaded the base64 library from the URL you provided, and linked it.

Now, code successfully executed.
 
It is worth noting that the "sgx-utils" project has been updated for the new version of SGX, which will cause error . (i recover the old version of "sgx-utils")

Thanks again for your help!

Cheers,
-Qing Hao,Wang
